spring.application.name=backend

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/csms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sandra143}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.ignore-migration-patterns=*:*
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

# ==========================
# Server
# ==========================
server.port=${PORT:8080}

# server.servlet.context-path=/
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.csms=DEBUG

spring.jackson.time-zone=Asia/Kolkata

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

jwt.secret=${JWT_SECRET:ThisIsMyVerySecretKeyForCampusServiceManagementSystemJWTAuthentication12345}
jwt.expiration=86400000


